version: "3"

services:
  web:
    container_name: ${APP_NAME}
    image: ${APP_NAME}/web
    build: 
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    # restart: no
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-developpement}
      HTTP_APP_PORT: ${HTTP_APP_PORT:-5173}
      APP_PATH: ${APP_PATH:-/var/www/app/}
    ports:
      - 5173:${HTTP_APP_PORT}
      # - ${HTTPS_APP_PORT}:8443
    volumes:
      - ./app/:${APP_PATH}
      - /var/www/app/node_modules

networks:
  default:
    name: ${NETWORK_NAME}
    external: true # network must have been created by another container
